# What's the highest network number?

In [25]:
import io
import json

from IPython.display import display
import ipywidgets as widgets
import polars as pl

In [2]:
uploader = widgets.FileUpload(
    accept=".geojson",
    multiple=False
)

In [3]:
uploader

FileUpload(value=(), accept='.geojson', description='Upload')

In [7]:
nodes_geojson = json.load(io.BytesIO(uploader.value[0].content))

In [18]:
nodes = pl.DataFrame([n["properties"] for n in nodes_geojson["features"]])

In [27]:
nodes.get_column("status").unique()

shape: (7,)
Series: 'status' [str]
[
	"Installed"
	"Surveyed"
	"Ready for Contact & Survey"
	"Needs Maintenance or realignme…
	"Ready for Install"
	"Purgatory"
	"Submitted Requests"
]

In [36]:
nodes_installed = (
    nodes
    .filter(pl.col("status").is_in(["Installed", "Needs Maintenance or realignment"]))
    .with_columns(
        pl.col("title").str.extract(r"^NN(\d+).*", 1).alias("network_number").cast(pl.Int32),
    )
    .sort("title")
)

In [37]:
with pl.Config(tbl_rows=-1):
    display(nodes_installed)

shape: (43, 4)
┌─────────────────────────────┬────────────────────────────┬──────────────────────┬────────────────┐
│ title                       ┆ link                       ┆ status               ┆ network_number │
│ ---                         ┆ ---                        ┆ ---                  ┆ ---            │
│ str                         ┆ str                        ┆ str                  ┆ i32            │
╞═════════════════════════════╪════════════════════════════╪══════════════════════╪════════════════╡
│ NN50 - BICAS                ┆ https://trello.com/c/YHdeV ┆ Needs Maintenance or ┆ 50             │
│                             ┆ n7n/…                      ┆ realignme…           ┆                │
│ NN51 - BICAS                ┆ https://trello.com/c/wkq19 ┆ Installed            ┆ 51             │
│                             ┆ 23u/…                      ┆                      ┆                │
│ NN53 - Abby, Ursula, Rosie  ┆ https://trello.com/c/mHDQS ┆ Installed            ┆ 53             │
│                             ┆ A2w/…                      ┆                      ┆                │
│ NN54 - Michael & Lovisa     ┆ https://trello.com/c/WBXio ┆ Needs Maintenance or ┆ 54             │
│                             ┆ BkF/…                      ┆ realignme…           ┆                │
│ NN55 - Outer Space 👽       ┆ https://trello.com/c/Nbpg3 ┆ Installed            ┆ 55             │
│                             ┆ 9Og/…                      ┆                      ┆                │
│ NN56 - ???                  ┆ https://trello.com/c/n9Z0d ┆ Needs Maintenance or ┆ 56             │
│                             ┆ VJn/…                      ┆ realignme…           ┆                │
│ NN57 - Steven Adger         ┆ https://trello.com/c/3wlzM ┆ Needs Maintenance or ┆ 57             │
│                             ┆ Dxc/…                      ┆ realignme…           ┆                │
│ NN58 - Rachel Wedig         ┆ https://trello.com/c/ykptr ┆ Installed            ┆ 58             │
│                             ┆ bqd/…                      ┆                      ┆                │
│ NN61 - Irene Gibbs          ┆ https://trello.com/c/fBKRE ┆ Installed            ┆ 61             │
│                             ┆ gpP/…                      ┆                      ┆                │
│ NN62 - Outlaw Project       ┆ https://trello.com/c/QCt1I ┆ Installed            ┆ 62             │
│                             ┆ moe/…                      ┆                      ┆                │
│ NN63 - Ryan Jordy Chava     ┆ https://trello.com/c/BWEVW ┆ Installed            ┆ 63             │
│                             ┆ xP5/…                      ┆                      ┆                │
│ NN64 - Mike Edmonds         ┆ https://trello.com/c/GjWNB ┆ Needs Maintenance or ┆ 64             │
│                             ┆ IR4/…                      ┆ realignme…           ┆                │
│ NN65 - CJ Boyd              ┆ https://trello.com/c/SXY2C ┆ Installed            ┆ 65             │
│                             ┆ EMo/…                      ┆                      ┆                │
│ NN66 - Randy Meisner COSIT  ┆ https://trello.com/c/HDUuQ ┆ Needs Maintenance or ┆ 66             │
│                             ┆ EUK/…                      ┆ realignme…           ┆                │
│ NN67 - Sadie Shaw           ┆ https://trello.com/c/l04z0 ┆ Installed            ┆ 67             │
│                             ┆ t3G/…                      ┆                      ┆                │
│ NN68 - Katie Bolger         ┆ https://trello.com/c/m3u8K ┆ Installed            ┆ 68             │
│                             ┆ 7px/…                      ┆                      ┆                │
│ NN69 - Aspen 💖             ┆ https://trello.com/c/0J4jK ┆ Installed            ┆ 69             │
│                             ┆ Vr4/…                      ┆                      ┆                │
│ NN70 - Trace Carroll        ┆ https://trello.com/c/9uIDy ┆ Installed            ┆ 70             │
│                             ┆ 2h4/…                      ┆                      ┆                │
│ NN71 - Kathleen Iris        ┆ https://trello.com/c/bGtaO ┆ Installed            ┆ 71             │
│ Coleman                     ┆ qhv/…                      ┆                      ┆                │
│ NN72 - Jackson              ┆ https://trello.com/c/MMwM1 ┆ Installed            ┆ 72             │
│                             ┆ gS6/…                      ┆                      ┆                │
│ NN73 - Steev Hise           ┆ https://trello.com/c/vQ6dy ┆ Needs Maintenance or ┆ 73             │
│                             ┆ uQC/…                      ┆ realignme…           ┆                │
│ NN75 - Richard Mayers       ┆ https://trello.com/c/fNcfS ┆ Installed            ┆ 75             │
│                             ┆ LgZ/…                      ┆                      ┆                │
│ NN76 - Antonieta Rodriguez  ┆ https://trello.com/c/8WcvC ┆ Installed            ┆ 76             │
│                             ┆ tLR/…                      ┆                      ┆                │
│ NN77 - Ian Fritz            ┆ https://trello.com/c/lSehe ┆ Installed            ┆ 77             │
│                             ┆ OU0/…                      ┆                      ┆                │
│ NN78 - Zalman Berkowitz     ┆ https://trello.com/c/82i61 ┆ Installed            ┆ 78             │
│                             ┆ 3De/…                      ┆                      ┆                │
│ NN79 - alison wood          ┆ https://trello.com/c/tOTYr ┆ Installed            ┆ 79             │
│                             ┆ uaV/…                      ┆                      ┆                │
│ NN80 - Tucson Food Share    ┆ https://trello.com/c/ftCz6 ┆ Needs Maintenance or ┆ 80             │
│                             ┆ yX8/…                      ┆ realignme…           ┆                │
│ NN81 - Jason moore          ┆ https://trello.com/c/tCNPm ┆ Needs Maintenance or ┆ 81             │
│                             ┆ pSg/…                      ┆ realignme…           ┆                │
│ NN82 - Everybody Gallery    ┆ https://trello.com/c/y9hUR ┆ Needs Maintenance or ┆ 82             │
│                             ┆ TRa/…                      ┆ realignme…           ┆                │
│ NN84 - Marjorie “Maggie”    ┆ https://trello.com/c/q54Pj ┆ Installed            ┆ 84             │
│ Crowd…                      ┆ hLU/…                      ┆                      ┆                │
│ NN85 and 86 - Leona Davis   ┆ https://trello.com/c/Xm0O3 ┆ Installed            ┆ 85             │
│ and …                       ┆ Msz/…                      ┆                      ┆                │
│ NN87 - Glen Frieden, King   ┆ https://trello.com/c/15Raq ┆ Installed            ┆ 87             │
│ of M…                       ┆ 4WB/…                      ┆                      ┆                │
│ NN88 - Noemie               ┆ https://trello.com/c/yQvoY ┆ Installed            ┆ 88             │
│ Despland-Lichter…           ┆ 8F7/…                      ┆                      ┆                │
│ NN89 - Ariel & LVD          ┆ https://trello.com/c/VXn88 ┆ Installed            ┆ 89             │
│                             ┆ Su0/…                      ┆                      ┆                │
│ NN90 - Wildcat Storage (BCC ┆ https://trello.com/c/baFUI ┆ Installed            ┆ 90             │
│ C2…                         ┆ EIc/…                      ┆                      ┆                │
│ NN91 - red                  ┆ https://trello.com/c/YkRln ┆ Installed            ┆ 91             │
│                             ┆ XJG/…                      ┆                      ┆                │
│ NN92 - Juliana              ┆ https://trello.com/c/vzHed ┆ Installed            ┆ 92             │
│                             ┆ 9Mb/…                      ┆                      ┆                │
│ NN93 - Alex/Moss            ┆ https://trello.com/c/b5H6Z ┆ Installed            ┆ 93             │
│                             ┆ N1s/…                      ┆                      ┆                │
│ NN94 - Hannah Lee           ┆ https://trello.com/c/82U3n ┆ Installed            ┆ 94             │
│                             ┆ rAH/…                      ┆                      ┆                │
│ NN95 - Ashley Edgette       ┆ https://trello.com/c/rBwyK ┆ Installed            ┆ 95             │
│                             ┆ QyO/…                      ┆                      ┆                │
│ NN96 - kelzi                ┆ https://trello.com/c/fuGxT ┆ Needs Maintenance or ┆ 96             │
│                             ┆ v7n/…                      ┆ realignme…           ┆                │
│ NN97 - Hannah and Moondog   ┆ https://trello.com/c/NQTp8 ┆ Installed            ┆ 97             │
│                             ┆ 9b7/…                      ┆                      ┆                │
│ NN98 - Geena, Rain, Marcel  ┆ https://trello.com/c/kgzS0 ┆ Installed            ┆ 98             │
│                             ┆ jKG/…                      ┆                      ┆                │
└─────────────────────────────┴────────────────────────────┴──────────────────────┴────────────────┘

In [38]:
network_number_max = nodes_installed.get_column("network_number").max()

In [39]:
network_number_max

98